//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotosManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Photo
    {
        const string PhotosFolder = @"/Images_Data/Photos/";
        const string DefaultPhoto = @"No_Image.png";

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Photo()
        {
            this.Likes = new HashSet<Like>();
            Image = PhotosFolder + DefaultPhoto;
            CreationDate = DateTime.Now;
        }
    
        public int Id { get; set; }
        public int OwnerId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        [Asset(PhotosFolder, DefaultPhoto)]
        public string Image { get; set; }
        public System.DateTime CreationDate { get; set; }
        public bool Shared { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Like> Likes { get; set; }
        public virtual User User { get; set; }
    }
}
